# Default values for huawei-cosi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##################################Follows are REQUIRED##################################
# all global values across charts go here
global:
  # the number of replicas of the pod.
  # if the replicaCount greater than 1, then the function of leader election will be enabled.
  replicaCount: 1

  # securityContext applies only to containers provided by Huawei, including cosiDriver and livenessProbe.
  securityContext:
    # indicates whether container run as a non-root user.
    # when runAsNonRoot is set to 'false', then parameter runAsGroup and runAsUser do not take effect.
    # Default value: false
    runAsNonRoot: false
    runAsUser: 1000
    runAsGroup: 1000

    # indicates whether container runs as a privileged container.
    # Default value: true
    enablePrivileged: true

  # Set the logging module and type.
  logging:
    # module supports 'file' and 'console'.
    module: file
    level: info
    fileSize: 20M
    maxBackups: 9

deploy:
  cosiController:
    # Whether to deploy cosiController.
    # Allowed values:
    #   true: deploy cosi-controller during installation.
    #   false: not deploy cosi-controller during installation.
    # Default value: true
    enabled: true
    # The namespace used for cosiController deployment.
    # Default value:  huawei-cosi
    namespace: huawei-cosi

    # Define node selection constraints for node pods.
    nodeSelector: {}
    # Tolerations allow the scheduler to schedule pods with matching taints
    tolerations: []
    # Affinity: constrain which nodes your Pod can be scheduled on based on node labels
    affinity: {}

  cosiProvisioner:
    # The namespace used for cosiProvisioner deployment.
    # Default value:  huawei-cosi
    namespace: huawei-cosi

    # The driver name of huawei-cosi driver.
    # Default value:  cosi.huawei.com
    driverName: cosi.huawei.com

    # Define node selection constraints for node pods.
    nodeSelector: {}
    # Tolerations allow the scheduler to schedule pods with matching taints
    tolerations: []
    # Affinity: constrain which nodes your Pod can be scheduled on based on node labels
    affinity: {}

images:
  # Images provided by Huawei-cosi
  driver:
    cosiDriver: huawei-cosi-driver:{{version}}
    livenessProbe: huawei-cosi-liveness-probe:{{version}}

  # COSI-related sidecar images provided by the Kubernetes community.
  # These must match the appropriate Kubernetes version.
  # The image versions we provided are verified.
  # Using other versions may lead unknown issues or unexpected behavior.
  controller:
    cosiController: gcr.io/k8s-staging-sig-storage/objectstorage-controller:v20250509-controllerv0.2.0-rc1-72-g945f40a
  sidecar:
    cosiSidecar: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar:v20250509-controllerv0.2.0-rc1-72-g945f40a

  # Default image pull policy for images, support [IfNotPresent, Always, Never]
  imagePullPolicy:
    huaweiCosiDriverImagePullPolicy: "IfNotPresent"
    huaweiCosiLivenessProbeImagePullPolicy: "IfNotPresent"
    cosiControllerImagePullPolicy: "IfNotPresent"
    cosiSidecarImagePullPolicy: "IfNotPresent"

  # Uses secrets to pull images from private container image registry or repository
  imagePullSecrets: []


# Specify the amount of CPU and memory resources that a container requires
resources:
# To disable the default configuration, comment out the following section.
  container:
    cosiDriver:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    cosiLivenessProbe:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
    cosiSidecar:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi
    cosiController:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi
